///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The cadastroClientes recording.
    /// </summary>
    [TestModule("57bdda0d-e7b2-4508-b2d1-e3cdf0b586e3", ModuleType.Recording, 1)]
    public partial class cadastroClientes : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static cadastroClientes instance = new cadastroClientes();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public cadastroClientes()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static cadastroClientes Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.MenuItemCadastros' at 45;4.", repo.SCVRetaguardaSistemaDeGestao.MenuItemCadastrosInfo, new RecordItemIndex(0));
            repo.SCVRetaguardaSistemaDeGestao.MenuItemCadastros.Click("45;4");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuSCV.MenuItem' at 63;13.", repo.ContextMenuSCV.MenuItemInfo, new RecordItemIndex(1));
            repo.ContextMenuSCV.MenuItem.Click("63;13");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuSCV.MenuItem' at 45;16.", repo.ContextMenuSCV.MenuItemInfo, new RecordItemIndex(2));
            repo.ContextMenuSCV.MenuItem.Click("45;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 518;199.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(3));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("518;199");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'teste' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(4));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("teste");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 446;666.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(5));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("446;666");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 538;197.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(6));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("538;197");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'teste ran' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(7));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("teste ran");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'orex' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(8));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("orex");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(9));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'ranorex{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(10));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("ranorex{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad8}{NumPad2}{NumPad7}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(11));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad8}{NumPad2}{NumPad7}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad7}{NumPad8}{NumPad5}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(12));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad7}{NumPad8}{NumPad5}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad9}{NumPad9}{NumPad0}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(13));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad9}{NumPad9}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad5}{NumPad6}{Tab}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(14));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad5}{NumPad6}{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ProblemasEncontrados'.", repo.ProblemasEncontrados.SelfInfo, new RecordItemIndex(15));
            repo.ProblemasEncontrados.Self.PressKeys("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 578;295.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(16));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("578;295");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(17));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='CPF inválido, verifique!\r\n') on item 'ProblemasEncontrados.MmoMensagem'.", repo.ProblemasEncontrados.MmoMensagemInfo, new RecordItemIndex(18));
            Validate.AttributeEqual(repo.ProblemasEncontrados.MmoMensagemInfo, "Text", "CPF inválido, verifique!\r\n");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProblemasEncontrados.OKEnter' at 62;28.", repo.ProblemasEncontrados.OKEnterInfo, new RecordItemIndex(19));
            repo.ProblemasEncontrados.OKEnter.Click("62;28");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 576;296.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(20));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("576;296");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 576;296.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(21));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.MoveTo("576;296");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 478;274.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(22));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.MoveTo("478;274");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad3}{NumPad1}{NumPad9}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(23));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad3}{NumPad1}{NumPad9}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad3}{NumPad2}{NumPad8}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(24));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad3}{NumPad2}{NumPad8}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad4}{NumPad7}{NumPad0}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(25));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad4}{NumPad7}{NumPad0}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad0}{NumPad6}{Tab}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(26));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad0}{NumPad6}{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 555;664.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(27));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("555;664");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 565;664.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(28));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("565;664");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 555;198.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(29));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("555;198");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '.' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(30));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(".");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 527;652.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(31));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("527;652");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 655;667.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(32));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("655;667");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Validation", "Validating AttributeEqual (Text='Confirma Exclusão do Registro ?') on item 'FrmNotificacao.MmoMensagem'.", repo.FrmNotificacao.MmoMensagemInfo, new RecordItemIndex(33));
            Validate.AttributeEqual(repo.FrmNotificacao.MmoMensagemInfo, "Text", "Confirma Exclusão do Registro ?");
            Delay.Milliseconds(100);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmNotificacao.ConfirmaEnter' at 203;32.", repo.FrmNotificacao.ConfirmaEnterInfo, new RecordItemIndex(34));
            repo.FrmNotificacao.ConfirmaEnter.Click("203;32");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 1206;92.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(35));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("1206;92");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
