///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The ClienteResumido recording.
    /// </summary>
    [TestModule("05c7df46-646b-4ab5-852f-7a378fcfb98a", ModuleType.Recording, 1)]
    public partial class ClienteResumido : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static ClienteResumido instance = new ClienteResumido();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public ClienteResumido()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static ClienteResumido Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.MenuItemCadastros' at 36;11.", repo.SCVRetaguardaSistemaDeGestao.MenuItemCadastrosInfo, new RecordItemIndex(0));
            repo.SCVRetaguardaSistemaDeGestao.MenuItemCadastros.Click("36;11");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuSCV.MenuItem1' at 99;19.", repo.ContextMenuSCV.MenuItem1Info, new RecordItemIndex(1));
            repo.ContextMenuSCV.MenuItem1.Click("99;19");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 438;659.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(2));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("438;659");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 532;199.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(3));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("532;199");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'jbkkjhgkjhg' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(4));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("jbkkjhgkjhg");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 504;232.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(5));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("504;232");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'kjh' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(6));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("kjh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 506;222.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(7));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("506;222");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 509;214.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(8));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("509;214");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'jhgkjhgkjh' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(9));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("jhgkjhgkjh");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 526;662.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(10));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("526;662");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 607;660.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(11));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("607;660");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmNotificacao.ConfirmaEnter' at 237;26.", repo.FrmNotificacao.ConfirmaEnterInfo, new RecordItemIndex(12));
            repo.FrmNotificacao.ConfirmaEnter.Click("237;26");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 702;653.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(13));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("702;653");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 718;659.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(14));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("718;659");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
