///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The fornecedor recording.
    /// </summary>
    [TestModule("d5faa500-5d07-4592-9f4c-cce71c283fd2", ModuleType.Recording, 1)]
    public partial class fornecedor : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static fornecedor instance = new fornecedor();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public fornecedor()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static fornecedor Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.MenuItemCadastros' at 46;14.", repo.SCVRetaguardaSistemaDeGestao.MenuItemCadastrosInfo, new RecordItemIndex(0));
            repo.SCVRetaguardaSistemaDeGestao.MenuItemCadastros.Click("46;14");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ContextMenuSCV.MenuItem' at 133;12.", repo.ContextMenuSCV.MenuItemInfo, new RecordItemIndex(1));
            repo.ContextMenuSCV.MenuItem.Click("133;12");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 498;645.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(2));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("498;645");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 633;200.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(3));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("633;200");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'teste' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(4));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("teste");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' ranorex{Tab}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(5));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(" ranorex{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'teste ranorex' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(6));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("teste ranorex");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 578;647.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(7));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("578;647");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ProblemasEncontrados'.", repo.ProblemasEncontrados.SelfInfo, new RecordItemIndex(8));
            repo.ProblemasEncontrados.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 593;274.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(9));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("593;274");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Left 17}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(10));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{Left 17}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad7}{NumPad5}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(11));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad7}{NumPad5}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}{NumPad3}{NumPad4}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(12));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad1}{NumPad3}{NumPad4}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad8}{NumPad2}{NumPad5}{NumPad0}{NumPad0}{NumPad0}{NumPad1}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(13));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad8}{NumPad2}{NumPad5}{NumPad0}{NumPad0}{NumPad0}{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad0}{NumPad6}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(14));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad0}{NumPad6}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Tab}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(15));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 591;662.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(16));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("591;662");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ProblemasEncontrados'.", repo.ProblemasEncontrados.SelfInfo, new RecordItemIndex(17));
            repo.ProblemasEncontrados.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 839;307.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(18));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("839;307");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(19));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 839;307.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(20));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("839;307");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad2 down}{NumPad3 down}{NumPad1 down}{NumPad2 up}{NumPad3 up}{NumPad3 down}{NumPad1 up}{NumPad2 down}{NumPad3 up}{NumPad1 down}{NumPad3 down}{NumPad2 up}{NumPad1 up}{NumPad3 up}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(21));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad2 down}{NumPad3 down}{NumPad1 down}{NumPad2 up}{NumPad3 up}{NumPad3 down}{NumPad1 up}{NumPad2 down}{NumPad3 up}{NumPad1 down}{NumPad3 down}{NumPad2 up}{NumPad1 up}{NumPad3 up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 575;661.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(22));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("575;661");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ProblemasEncontrados'.", repo.ProblemasEncontrados.SelfInfo, new RecordItemIndex(23));
            repo.ProblemasEncontrados.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 586;656.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(24));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("586;656");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'ProblemasEncontrados.OKEnter' at 56;50.", repo.ProblemasEncontrados.OKEnterInfo, new RecordItemIndex(25));
            repo.ProblemasEncontrados.OKEnter.Click("56;50");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 555;297.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(26));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("555;297");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(27));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad1}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 565;316.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(28));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("565;316");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'Explorer.SCVExeAtalho21ExecutandoOWi' at 25;-133.", repo.Explorer.SCVExeAtalho21ExecutandoOWiInfo, new RecordItemIndex(29));
            repo.Explorer.SCVExeAtalho21ExecutandoOWi.Click("25;-133");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ProblemasEncontrados'.", repo.ProblemasEncontrados.SelfInfo, new RecordItemIndex(30));
            repo.ProblemasEncontrados.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 757;428.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(31));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("757;428");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ConsultaCadastroDeCidades'.", repo.ConsultaCadastroDeCidades.SelfInfo, new RecordItemIndex(32));
            repo.ConsultaCadastroDeCidades.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 588;653.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(33));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("588;653");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ProblemasEncontrados'.", repo.ProblemasEncontrados.SelfInfo, new RecordItemIndex(34));
            repo.ProblemasEncontrados.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Down item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 570;380.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(35));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.MoveTo("570;380");
            Mouse.ButtonDown(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Up item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 464;367.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(36));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.MoveTo("464;367");
            Mouse.ButtonUp(System.Windows.Forms.MouseButtons.Left);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad7 down}{NumPad9 down}{NumPad7 up}{NumPad9 up}{NumPad0}{NumPad1}{NumPad1}{NumPad0}{NumPad3}{NumPad0}{Return down}{Tab down}{Return up}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(37));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad7 down}{NumPad9 down}{NumPad7 up}{NumPad9 up}{NumPad0}{NumPad1}{NumPad1}{NumPad0}{NumPad3}{NumPad0}{Return down}{Tab down}{Return up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 585;433.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(38));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("585;433");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1 down}{NumPad2 down}{NumPad3 down}{NumPad1 up}{NumPad2 up}{NumPad3 up}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(39));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad1 down}{NumPad2 down}{NumPad3 down}{NumPad1 up}{NumPad2 up}{NumPad3 up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 605;657.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(40));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("605;657");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Return}' with focus on 'ProblemasEncontrados'.", repo.ProblemasEncontrados.SelfInfo, new RecordItemIndex(41));
            repo.ProblemasEncontrados.Self.EnsureVisible();
            Keyboard.Press("{Return}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 623;455.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(42));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("623;455");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{NumPad1 down}{NumPad2 down}{NumPad3 down}{NumPad1 up}{NumPad2 up}{NumPad3 up}{Tab}{NumPad1 down}{NumPad2 down}{NumPad3 down}{NumPad1 up}{NumPad2 up}{NumPad3 up}{Tab}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad3 down}{NumPad2 up}{NumPad3 up}' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(43));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press("{NumPad1 down}{NumPad2 down}{NumPad3 down}{NumPad1 up}{NumPad2 up}{NumPad3 up}{Tab}{NumPad1 down}{NumPad2 down}{NumPad3 down}{NumPad1 up}{NumPad2 up}{NumPad3 up}{Tab}{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad3 down}{NumPad2 up}{NumPad3 up}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 578;657.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(44));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("578;657");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 693;657.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(45));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("693;657");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmNotificacao.CancelarEsc' at 68;35.", repo.FrmNotificacao.CancelarEscInfo, new RecordItemIndex(46));
            repo.FrmNotificacao.CancelarEsc.Click("68;35");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 566;655.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(47));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("566;655");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 667;197.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(48));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("667;197");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence ' alteracao' with focus on 'FrmPrincipal'.", repo.FrmPrincipal.SelfInfo, new RecordItemIndex(49));
            repo.FrmPrincipal.Self.EnsureVisible();
            Keyboard.Press(" alteracao");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 574;651.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(50));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("574;651");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmPrincipal.VersaoDeTestesNaoUsarEmProducao' at 682;662.", repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducaoInfo, new RecordItemIndex(51));
            repo.FrmPrincipal.VersaoDeTestesNaoUsarEmProducao.Click("682;662");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'FrmNotificacao.ConfirmaEnter' at 187;35.", repo.FrmNotificacao.ConfirmaEnterInfo, new RecordItemIndex(52));
            repo.FrmNotificacao.ConfirmaEnter.Click("187;35");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
