///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace MyTest
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The Login recording.
    /// </summary>
    [TestModule("38c45834-83a0-4a28-a497-d83bb693a8fd", ModuleType.Recording, 1)]
    public partial class Login : ITestModule
    {
        /// <summary>
        /// Holds an instance of the MyTestRepository repository.
        /// </summary>
        public static MyTestRepository repo = MyTestRepository.Instance;

        static Login instance = new Login();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public Login()
        {
            scv = "scv.exe";
            caminhoSCV = "C:\\SCV\\RETAGUARDA\\EXE";
            cpfUsuario = "{NumPad1 down}{NumPad2 down}{NumPad1 up}{NumPad3 down}{NumPad2 up}{NumPad3 up}{NumPad4 down}{NumPad5 down}{NumPad4 up}{NumPad6 down}{NumPad5 up}{NumPad4 down}{NumPad8 down}{NumPad6 up}{NumPad4 up}{NumPad7 down}{NumPad8 up}{NumPad8 down}{NumPad7 up}{NumPad8 up}{NumPad8}{Tab}";
            cpfCliente = "97706631079";
            senhaDia = "5828";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static Login Instance
        {
            get { return instance; }
        }

#region Variables

        string _scv;

        /// <summary>
        /// Gets or sets the value of variable scv.
        /// </summary>
        [TestVariable("46c62935-9f58-4e06-8614-1d18585dec55")]
        public string scv
        {
            get { return _scv; }
            set { _scv = value; }
        }

        string _caminhoSCV;

        /// <summary>
        /// Gets or sets the value of variable caminhoSCV.
        /// </summary>
        [TestVariable("53b800a8-6edc-4ef6-9f23-5cda490c5a2c")]
        public string caminhoSCV
        {
            get { return _caminhoSCV; }
            set { _caminhoSCV = value; }
        }

        string _cpfUsuario;

        /// <summary>
        /// Gets or sets the value of variable cpfUsuario.
        /// </summary>
        [TestVariable("52897088-5e93-40a9-8321-a1022be762b7")]
        public string cpfUsuario
        {
            get { return _cpfUsuario; }
            set { _cpfUsuario = value; }
        }

        string _cpfCliente;

        /// <summary>
        /// Gets or sets the value of variable cpfCliente.
        /// </summary>
        [TestVariable("0b96d97c-cb06-4fbe-b240-f635c3f87e54")]
        public string cpfCliente
        {
            get { return _cpfCliente; }
            set { _cpfCliente = value; }
        }

        string _senhaDia;

        /// <summary>
        /// Gets or sets the value of variable senhaDia.
        /// </summary>
        [TestVariable("3c2eac70-969e-4078-8d30-b65d1ef8c0bf")]
        public string senhaDia
        {
            get { return _senhaDia; }
            set { _senhaDia = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Application", "Run application with file name from variable $scv in normal mode. Return value bound to $scv.", new RecordItemIndex(0));
            scv = ValueConverter.ToString(Host.Local.RunApplication(scv, "", caminhoSCV, false));
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguarda.EdtLogin' at 117;16.", repo.SCVRetaguarda.EdtLoginInfo, new RecordItemIndex(1));
            repo.SCVRetaguarda.EdtLogin.Click("117;16");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key 'Ctrl+A' Press with focus on 'SCVRetaguarda.EdtLogin'.", repo.SCVRetaguarda.EdtLoginInfo, new RecordItemIndex(2));
            Keyboard.PrepareFocus(repo.SCVRetaguarda.EdtLogin);
            Keyboard.Press(System.Windows.Forms.Keys.A | System.Windows.Forms.Keys.Control, 30, Keyboard.DefaultKeyPressTime, 1, true);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Home}{LShiftKey down}{End}{LShiftKey up}scvsup{Tab}' with focus on 'SCVRetaguarda.EdtLogin'.", repo.SCVRetaguarda.EdtLoginInfo, new RecordItemIndex(3));
            repo.SCVRetaguarda.EdtLogin.PressKeys("{Home}{LShiftKey down}{End}{LShiftKey up}scvsup{Tab}");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$senhaDia' with focus on 'SCVRetaguarda'.", repo.SCVRetaguarda.SelfInfo, new RecordItemIndex(4));
            repo.SCVRetaguarda.Self.EnsureVisible();
            Keyboard.Press(senhaDia);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguarda.ButtonLogar' at 56;10.", repo.SCVRetaguarda.ButtonLogarInfo, new RecordItemIndex(5));
            repo.SCVRetaguarda.ButtonLogar.Click("56;10");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 1274;117.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(6));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("1274;117");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 1134;141.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(7));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("1134;141");
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'SCVRetaguardaSistemaDeGestao.ImgPrincipal' at 1160;130.", repo.SCVRetaguardaSistemaDeGestao.ImgPrincipalInfo, new RecordItemIndex(8));
            repo.SCVRetaguardaSistemaDeGestao.ImgPrincipal.Click("1160;130");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
